### ISSUE TITLE
Add macOS arm64 to Goreleaser

### ISSUE THREAD

**Issue by crgimenes** [crgimenes/neko#10]

**Comment by glensc** [comment]
yeah, go is cross platform yet no arm64 build for macos.

**Comment by crgimenes** [comment]
> yeah, go is cross platform yet no arm64 build for macos.

Go is cross-platform, but a small part of Neko needs to be written in C to interact with the operating system.

While I can compile and run on my Mac, automating the build to upload to GitHub is tricky because I need to automate multiple platforms simultaneously.

I'm working on it, but it's a complex task.
