### ISSUE TITLE
Not Working On New Macs

### ISSUE THREAD

**Issue by bearsystems** [crgimenes/neko#36]
I am trying to get the code working on a new Mac laptop purchased late last year and the build will not compile.  Do you have any ideas what might need to be updated or changed?

Thank you!

**Comment by crgimenes** [comment]
Can you send more details? What error message are you getting?

**Comment by bearsystems** [comment]
Thank you Cesar, for responding so quickly and I apologize for the delay in getting back to you.  I am trying to compile on Sonoma version 14.3.

 

Here is the error message:

**Comment by crgimenes** [comment]
The error is not appearing in the message, I imagine you tried to send it as an image and there is some incompatibility with github.

**Comment by bearsystems** [comment]
Here is it
<img width="707" alt="Error" src="https://github.com/user-attachments/assets/f85e6fae-4025-4a20-b09e-cac72816316e">

**Comment by crgimenes** [comment]
You accidentally deleted the word Neko, which is the name of the struct. You probably hit the space bar. I'm sending the link to this line of code in the repository; see how different it is.

https://github.com/crgimenes/neko/blob/master/main.go#L25

**Comment by bearsystems** [comment]
Thank you Cesar, I just redownloaded all of your code to correct the issue, I am now getting the following error

 

The field values – min, max, and state – are not defined.  Do I need to define these somewhere – I am using the VS Code via GitHub.

**Comment by crgimenes** [comment]
The code is prepared for compilation, so there's no need to declare these variables. You can proceed with the compilation process.
Instead of VSC, use the make command directly on the command line. It should correctly compile the code for you.

**Comment by crgimenes** [comment]
Also, note that GitHub does not accept images sent by email. I don't know if your last issue had an image with more information.
Please use the GitHub web interface instead of email.
