### ISSUE TITLE
MousePassThrough option for windows version

### ISSUE THREAD

**Issue by im-izz** [crgimenes/neko#37]
-mousepassthrough parameter doesn't work in windows

**Comment by crgimenes** [comment]
Unfortunately, I don't have Windows machines to test the problem.

**Comment by im-izz** [comment]
This is what I get tho, Might that be helpful

![image](https://github.com/user-attachments/assets/53a1e39c-e0dc-4623-99f5-d35331a12ab5)

**Comment by arrlancore** [comment]
hi @crgimenes I have a Windows machine set up for testing, I'd be happy to help fix this. can you assign to me?

**Comment by crgimenes** [comment]
> hi @crgimenes I have a Windows machine set up for testing, I'd be happy to help fix this. can you assign to me?

Thanks for the help! I believe the problem is with Ebitengine, but I'm not sure, I didn't find any issues about it.

**Comment by arrlancore** [comment]
yes correct, there no issue in my windows machine with latest version go.
![image](https://github.com/user-attachments/assets/f87e7fb9-621a-4f90-82ce-c70e24ca85b8)

**Comment by im-izz** [comment]
Yay :D, so where to update or get the binary?
